// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZgUfelnao1rBvT53VlZETmmktvzIkI4',
    appId: '1:725005863356:web:daf9b0f8dfafdfbbe883b9',
    messagingSenderId: '725005863356',
    projectId: 'sexpedition-55',
    authDomain: 'sexpedition-55.firebaseapp.com',
    storageBucket: 'sexpedition-55.firebasestorage.app',
    measurementId: 'G-X9VVWRJ1YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4KrUZYRsi0MphsbXqTo8tGiRqIqvp3AI',
    appId: '1:725005863356:android:a0e9da59a7291f11e883b9',
    messagingSenderId: '725005863356',
    projectId: 'sexpedition-55',
    storageBucket: 'sexpedition-55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmu58XNvk6mqyQpNmmHq5HwGwOChUDYw',
    appId: '1:725005863356:ios:b199199c1edf9063e883b9',
    messagingSenderId: '725005863356',
    projectId: 'sexpedition-55',
    storageBucket: 'sexpedition-55.firebasestorage.app',
    iosBundleId: 'com.example.sexpeditionApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmu58XNvk6mqyQpNmmHq5HwGwOChUDYw',
    appId: '1:725005863356:ios:b199199c1edf9063e883b9',
    messagingSenderId: '725005863356',
    projectId: 'sexpedition-55',
    storageBucket: 'sexpedition-55.firebasestorage.app',
    iosBundleId: 'com.example.sexpeditionApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ZgUfelnao1rBvT53VlZETmmktvzIkI4',
    appId: '1:725005863356:web:1ebc755032fae02ae883b9',
    messagingSenderId: '725005863356',
    projectId: 'sexpedition-55',
    authDomain: 'sexpedition-55.firebaseapp.com',
    storageBucket: 'sexpedition-55.firebasestorage.app',
    measurementId: 'G-YQ19GX2Z82',
  );
}
